export const AUTH_LOGIN_BEGIN            = 'AUTH_LOGIN_BEGIN';
export const AUTH_LOGIN_COMPLETE         = 'AUTH_LOGIN_COMPLETE';
export const AUTH_LOGIN_FAILURE          = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT_BEGIN           = 'AUTH_LOGOUT_BEGIN';
export const AUTH_LOGOUT_COMPLETE        = 'AUTH_LOGOUT_COMPLETE';
export const AUTH_TOGGLE_LOGIN_DIALOG    = 'AUTH_TOGGLE_LOGIN_DIALOG';
export const AUTH_TOGGLE_REGISTER_DIALOG = 'AUTH_TOGGLE_REGISTER_DIALOG';
export const AUTH_RESET                  = 'AUTH_RESET';

export const REGISTER_TOGGLE_DIALOG  = 'REGISTER_TOGGLE_DIALOG';
export const REGISTER_RESET          = 'REGISTER_RESET';

export const NAV_TOGGLE_DRAWER   = 'NAV_TOGGLE_DRAWER';

export const ROOM_SET_NAME     = 'ROOM_SET_NAME';
export const ROOM_INPUT_CHANGE = 'ROOM_INPUT_CHANGE';
export const ROOM_INPUT_SEND   = 'ROOM_INPUT_SEND';
