<?php

namespace AppBundle\Entity;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends AbstractRepository
{
}
